title: Aditya Gupta's Blog
description: ML infrastructure engineer at Google. Notes on algorithms, chess, systems, and whatever else.
email: adityagupta1089@gmail.com
baseurl: ""
url: "https://adityagupta1089.github.io"

github_username: adityagupta1089
linkedin_username: aaditya-gupta
strava_id: 107970902
soundcloud_username: aditya-gupta-580893073
mathse_username: 67609/re60k

theme-dark: false

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-compose
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - slash-div

permalink: none

category_dir: 'categories'
category_title_prefix: ''

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  permalink: '/page/:num/'
  title: 'Page :num'
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    layouts:
      - 'autopage_category.html'
    title: ':cat'
    permalink: '/category/:cat'
  collections:
    enabled: false
